---
version: '2.0'
services:
  web:
    image: weaming/2captcha-pool
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "127.0.0.1:5000:5000"
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
      - $DOTFILES/etc/redis/redis.conf:/etc/redis/redis.conf
volumes:
  redisdata: {}
